from tkinter import *
window = Tk()
window.title("Simple Calculator")
# window.geometry('400x500+0+0')
def add_button():
    return
    # entry.value = str()


entry = Entry(window, width=35, borderwidth=5)  # ,font=('arial', 50, 'bold'))
entry.grid(row=0, column=0, columnspan=3, padx=5, pady=5)

b_one = Button(window, bg='grey', text='1', padx=25, pady=15, command=add_button)
b_two = Button(window, bg='grey', text='2', padx=25, pady=15, command=add_button)
b_three = Button(window, bg='grey',  text='3', padx=25, pady=15, command=add_button)
b_four = Button(window, bg='grey', text='4', padx=25, pady=15, command=add_button)
b_five = Button(window, bg='grey', text='5', padx=25, pady=15, command=add_button)
b_six = Button(window, bg='grey', text='6', padx=25, pady=15, command=add_button)
b_seven = Button(window, bg='grey', text='7', padx=25, pady=15, command=add_button)
b_eight = Button(window, bg='grey', text='8', padx=25, pady=15, command=add_button)
b_nine = Button(window, bg='grey', text='9', padx=25, pady=15, command=add_button)
b_zero = Button(window, bg='grey', text='0', padx=25, pady=15, command=add_button)
b_plus = Button(window, bg='violet', text='+', padx=25, pady=15, command=add_button)
b_minus = Button(window, bg='violet', text='-', padx=25, pady=15, command=add_button)
b_multiply = Button(window, bg='violet', text='x', padx=25, pady=15, command=add_button)
b_divide = Button(window, bg='violet', text='/', padx=25, pady=15, command=add_button)
b_ans = Button(window, bg='#42f5bc', text='=', padx=25, pady=15, command=add_button)
b_clr = Button(window, bg='#42f5bc', text='C', padx=25, pady=15, command=add_button)
b_left_bracket = Button(window, bg='violet', text='(', padx=25, pady=15, command=add_button)
b_right_bracket = Button(window, bg='violet', text=')', padx=25, pady=15, command=add_button)
b_point = Button(window, bg='violet', text='.', padx=25, pady=15, command=add_button)
b_sqrt = Button(window, bg='violet', text='√', padx=25, pady=15, command=add_button)

b_one.grid(row=2, column=0)
b_two.grid(row=2, column=1)
b_three.grid(row=2, column=2)
b_four.grid(row=3, column=0)
b_five.grid(row=3, column=1)
b_six.grid(row=3, column=2)
b_seven.grid(row=4, column=0)
b_eight.grid(row=4, column=1)
b_nine.grid(row=4, column=2)
b_zero.grid(row=1, column=0)
b_ans.grid(row=1, column=1)
b_clr.grid(row=1, column=2)
b_plus.grid(row=1, column=3)
b_minus.grid(row=2, column=3)
b_multiply.grid(row=3, column=3)
b_divide.grid(row=4, column=3)
b_left_bracket.grid(row=5, column=0)
b_right_bracket.grid(row=5, column=1)
b_point.grid(row=5, column=2)
b_sqrt.grid(row=5, column=3)

window.mainloop()
